# rename it .config.yml

telegram:
  token: 123:put_your_telegram_token_here

db:
  redis:
    url: 'redis://thb_redis:6379/7'
    db: 7

admin:
  list:
    - 123

# set false for production!
debug: true

periodic:
  period: 1m

weight_aim:
  calc:
    smooth_period: 4